language: php

sudo: false

env:
  global:
  - secure: PENfjgcItjkcdkDjZZABlQzrcSDDgtAR5uJ/bTFJ+lryS675X5V/2nzSikxkpx0NvIBvj4N6ooQZDG/WsDNsNL9SYPjeEcmW60ADxs8SBU3+SczBIEIK3IN/5Cdmfrx0HrmuShMe6gkV07ZT1/Jhch1WExapfssZ9eniPqDkECE=

matrix:
  include:
    - php: '5.3'
    - php: '5.4'
    - php: '5.5'
    - php: '5.6'
      env:
        - EXECUTE_AFTER_SCRIPT=true

addons:
  apt:
    packages:
    - graphviz
    
cache:
  directories:
  - "$HOME/.composer/cache"
  
before_install:
- mkdir -p ~/.composer
- cp .travis.composer.json ~/.composer/config.json
- composer self-update
- composer install --prefer-dist --dev
- pear channel-discover pear.phpdoc.org
- pear install phpdoc/phpDocumentor
- phpenv rehash

before_script:
- mkdir -p build/{logs,coverage,phpdoc}

script:
- cd tests
- phpunit -d max_execution_time=0 --coverage-text --coverage-clover ../build/logs/clover.xml --coverage-html ../build/coverage/
- cd ..

after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then php vendor/bin/coveralls --verbose --config;fi
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then phpdoc -d "./src" -t "./build/phpdoc" --template="responsive-twig";fi
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then bash <(curl -s https://gist.githubusercontent.com/neilime/769d733c52acdecea8d2548fb3aca3ff/raw/travis_ci_php_publish_build.sh);fi
