language: php
sudo: false
env:
  global:
  - secure: hjYJ4P2sgF/35VUdAxhY/I8KhTWBkb0fl4HM9qlVXeX44vKTl89zTJoTIRpnE3+rL3aiFOn5PJh4a8qxHV8euCyb1muPRPN4PL5qmnxNoAYyu1A1z7SqE0ORaRhRLFnNxVtLo6YM1zc/m5zrv67L5Jvt8ZLyr01bsuORVLnZ6mw=

matrix:
  include:
  - php: '7.0'
    env:
    - EXECUTE_AFTER_SCRIPT=true

cache:
  directories:
  - "$HOME/.composer/cache"
  
before_install:
- travis_retry composer self-update
- travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
- composer test:ci

after_script:
- if [[ $EXECUTE_AFTER_SCRIPT == 'true' ]]; then bash <(curl -s https://gist.githubusercontent.com/neilime/769d733c52acdecea8d2548fb3aca3ff/raw/travis_ci_php_publish_build.sh);fi