<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Neilime\AssetsBundle\Module' => __DIR__ . '/Module.php',
    'Neilime\AssetsBundleTest\Framework\TestCase' => __DIR__ . '/tests/AssetsBundle/Framework/TestCase.php',
    'Neilime\AssetsBundleTest\SampleTest' => __DIR__ . '/tests/AssetsBundle/SampleTest.php',
	'Neilime\AssetsBundle\Factory\ServiceFactory' => __DIR__ . '/src/AssetsBundle/Factory/ServiceFactory.php',
	'Neilime\AssetsBundle\Factory\Filter\CssFilterFactory' => __DIR__ . '/src/AssetsBundle/Factory/Filter/CssFilterFactory.php',
	'Neilime\AssetsBundle\Factory\Filter\JsFilterFactory' => __DIR__ . '/src/AssetsBundle/Factory/Filter/JsFilterFactory.php',
	'Neilime\AssetsBundle\Factory\Filter\LessFilterFactory' => __DIR__ . '/src/AssetsBundle/Factory/Filter/LessFilterFactory.php',
	'Neilime\AssetsBundle\Mvc\Controller\AbstractActionController' => __DIR__ . '/src/AssetsBundle/Mvc/Controller/AbstractActionController.php',
	'Neilime\AssetsBundle\Service\Filter\CssFilter' => __DIR__ . '/src/AssetsBundle/Service/Filter/CssFilter.php',
	'Neilime\AssetsBundle\Service\Filter\JsFilter' => __DIR__ . '/src/AssetsBundle/Service/Filter/JsFilter.php',
	'Neilime\AssetsBundle\Service\Filter\LessFilter' => __DIR__ . '/src/AssetsBundle/Service/Filter/LessFilter.php',
	'Neilime\AssetsBundle\Service\Filter\FilterInterface' => __DIR__ . '/src/AssetsBundle/Service/Filter/FilterInterface.php',
	'Neilime\AssetsBundle\Service\Service' => __DIR__ . '/src/AssetsBundle/Service/Service.php',
	'Neilime\AssetsBundle\View\Renderer\JsRenderer' => __DIR__ . '/src/AssetsBundle/View/Renderer/JsRenderer.php',
	'Neilime\AssetsBundle\View\Strategy\AbstractStrategy' => __DIR__ . '/src/AssetsBundle/View/Strategy/AbstractStrategy.php',
	'Neilime\AssetsBundle\View\Strategy\JsCustomStrategy' => __DIR__ . '/src/AssetsBundle/View/Strategy/JsCustomStrategy.php',
	'Neilime\AssetsBundle\View\Strategy\NoneStrategy' => __DIR__ . '/src/AssetsBundle/View/Strategy/NoneStrategy.php',
	'Neilime\AssetsBundle\View\Strategy\StrategyInterface' => __DIR__ . '/src/AssetsBundle/View/Strategy/StrategyInterface.php',
	'Neilime\AssetsBundle\View\Strategy\ViewHelperStrategy' => __DIR__ . '/src/AssetsBundle/View/Strategy/ViewHelperStrategy.php',
	//JSMin don't have autoloader
	'JSMin\Minify' =>  __DIR__ . '/../../nick4fake/jsmin/JsMin/Minify.php'
);
