<?php
return array(
	'AssetsBundle\Module' 								   => __DIR__ . '/Module.php',
	'AssetsBundle\Controller\ToolsController'              => __DIR__ . '/src/AssetsBundle/Controller/ToolsController.php',
	'AssetsBundle\Factory\Filter\CssFilterFactory'         => __DIR__ . '/src/AssetsBundle/Factory/Filter/CssFilterFactory.php',
	'AssetsBundle\Factory\Filter\GifFilterFactory'         => __DIR__ . '/src/AssetsBundle/Factory/Filter/GifFilterFactory.php',
	'AssetsBundle\Factory\Filter\JpegFilterFactory'        => __DIR__ . '/src/AssetsBundle/Factory/Filter/JpegFilterFactory.php',
	'AssetsBundle\Factory\Filter\JsFilterFactory'          => __DIR__ . '/src/AssetsBundle/Factory/Filter/JsFilterFactory.php',
	'AssetsBundle\Factory\Filter\LessFilterFactory'        => __DIR__ . '/src/AssetsBundle/Factory/Filter/LessFilterFactory.php',
	'AssetsBundle\Factory\Filter\PngFilterFactory'         => __DIR__ . '/src/AssetsBundle/Factory/Filter/PngFilterFactory.php',
	'AssetsBundle\Factory\JsCustomRendererFactory'         => __DIR__ . '/src/AssetsBundle/Factory/JsCustomRendererFactory.php',
	'AssetsBundle\Factory\JsCustomStrategyFactory'         => __DIR__ . '/src/AssetsBundle/Factory/JsCustomStrategyFactory.php',
	'AssetsBundle\Factory\ServiceFactory'                  => __DIR__ . '/src/AssetsBundle/Factory/ServiceFactory.php',
	'AssetsBundle\Mvc\Controller\AbstractActionController' => __DIR__ . '/src/AssetsBundle/Mvc/Controller/AbstractActionController.php',
	'AssetsBundle\Service\Filter\AbstractImageFilter'      => __DIR__ . '/src/AssetsBundle/Service/Filter/AbstractImageFilter.php',
	'AssetsBundle\Service\Filter\CssFilter'                => __DIR__ . '/src/AssetsBundle/Service/Filter/CssFilter.php',
	'AssetsBundle\Service\Filter\FilterInterface'          => __DIR__ . '/src/AssetsBundle/Service/Filter/FilterInterface.php',
	'AssetsBundle\Service\Filter\GifFilter'                => __DIR__ . '/src/AssetsBundle/Service/Filter/GifFilter.php',
	'AssetsBundle\Service\Filter\JpegFilter'               => __DIR__ . '/src/AssetsBundle/Service/Filter/JpegFilter.php',
	'AssetsBundle\Service\Filter\JsFilter'                 => __DIR__ . '/src/AssetsBundle/Service/Filter/JsFilter.php',
	'AssetsBundle\Service\Filter\LessFilter'               => __DIR__ . '/src/AssetsBundle/Service/Filter/LessFilter.php',
	'AssetsBundle\Service\Filter\PngFilter'                => __DIR__ . '/src/AssetsBundle/Service/Filter/PngFilter.php',
	'AssetsBundle\Service\Service'                         => __DIR__ . '/src/AssetsBundle/Service/Service.php',
	'AssetsBundle\View\Renderer\JsCustomRenderer'          => __DIR__ . '/src/AssetsBundle/View/Renderer/JsCustomRenderer.php',
	'AssetsBundle\View\Strategy\AbstractStrategy'          => __DIR__ . '/src/AssetsBundle/View/Strategy/AbstractStrategy.php',
	'AssetsBundle\View\Strategy\JsCustomStrategy'          => __DIR__ . '/src/AssetsBundle/View/Strategy/JsCustomStrategy.php',
	'AssetsBundle\View\Strategy\NoneStrategy'              => __DIR__ . '/src/AssetsBundle/View/Strategy/NoneStrategy.php',
	'AssetsBundle\View\Strategy\StrategyInterface'         => __DIR__ . '/src/AssetsBundle/View/Strategy/StrategyInterface.php',
	'AssetsBundle\View\Strategy\ViewHelperStrategy'        => __DIR__ . '/src/AssetsBundle/View/Strategy/ViewHelperStrategy.php',
);
